#!/bin/sh
echo "Setting up content-mgr variables"
echo "make sure you invoke this with: "
echo "source ./env.sh"
echo "setting PORT"
export PORT="8080"
echo "setting HOST"
export HOST="localhost"
echo "setting AZURE_STORAGE_CONNECTION_STRING"
export AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=xxxx;AccountKey=yyyyyyyyyyy"
echo "setting FILE_CONTAINER_NAME"
export FILE_CONTAINER_NAME="files"
echo "setting IMG_CONTAINER_NAME"
export IMG_CONTAINER_NAME="images"
echo "setting UNLINK_TIMEOUT"
export UNLINK_TIMEOUT="2000"
echo "setting JWT_KEY"
export JWT_KEY="jwt-secret-key-here"

